# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port.external }}
      targetPort: {{ .Values.service.port.container }}
  type: LoadBalancer
