name: app
replicas: 1

image:
  repository: luiyi/deel-devops-challenge
  tag: 0.0.3

service:
  port:
    container: 5000
    external: 80

env:
  DATABASE_URL: "postgresql://username:password@app-postgresql:5432/database"

postgresql:
  global:
    postgresql:
      auth:
        username: "username"
        password: "password"
        database: "database"
        postgresPassword: "password"
