name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: luiyi/deel-devops-challenge:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jmagnusson/deploy-helm-gke-action@v1
        with:
          docker-image-repo: luiyi/deel-devops-challenge
          docker-image-tag: ${{ github.sha }}
          helm-release-name: app
          helm-chart-path: ./helm
          helm-vars-folder: ./helm
          gke-project: deel-devops-challenge
          gke-cluster: deel-devops-challenge
          gke-zone: us-central1
          gke-sa-key: ${{ secrets.GKE_SA_KEY }}
